"""initial migration

Revision ID: 942343830668
Revises: 2d360b05ea89
Create Date: 2025-01-29 15:52:05.102261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '942343830668'
down_revision: Union[str, None] = '2d360b05ea89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diet_plans', sa.Column('date', sa.String(), nullable=True))
    op.add_column('food_items', sa.Column('protein', sa.Integer(), nullable=True))
    op.add_column('food_items', sa.Column('carbs', sa.Integer(), nullable=True))
    op.add_column('food_items', sa.Column('fats', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('weight', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('height', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('activity_level', sa.String(), nullable=True))
    op.add_column('users', sa.Column('goal', sa.String(), nullable=True))
    op.add_column('users', sa.Column('dietary_preferences', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'dietary_preferences')
    op.drop_column('users', 'goal')
    op.drop_column('users', 'activity_level')
    op.drop_column('users', 'height')
    op.drop_column('users', 'weight')
    op.drop_column('users', 'age')
    op.drop_column('food_items', 'fats')
    op.drop_column('food_items', 'carbs')
    op.drop_column('food_items', 'protein')
    op.drop_column('diet_plans', 'date')
    # ### end Alembic commands ###
